---
- name: Update Windows devices
  hosts: windows
  gather_facts: false
  tasks:
  - name: Install all Windows updates
    win_updates:
      category_names:
        - CriticalUpdates
        - SecurityUpdates
      state: installed
      reboot: false
  - name: Reboot if required
    win_reboot:
    when: win_updates_result.reboot_required
