---
- name: Update Windows devices
  hosts: windows
  gather_facts: false
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5986
  tasks:
  - name: Install all Windows updates
    win_updates:
      category_names:
        - CriticalUpdates
        - SecurityUpdates
      state: installed
      reboot: false
    register: win_updates_result
  - name: Reboot if required
    win_reboot:
    when: win_updates_result.reboot_required
