- name: Configure Ubuntu hosts with core packages
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Run tasks only on Ubuntu systems
      when: ansible_facts['distribution'] == "Ubuntu"
      block:
        - name: Install core packages (common)
          apt:
            name:
              - nano
              - bashtop
              - cifs-utils
            state: present
            update_cache: yes
            cache_valid_time: 3600

        - name: Install qemu-guest-agent (Proxmox VMs only)
          apt:
            name:
              - qemu-guest-agent
            state: present
            update_cache: yes
            cache_valid_time: 3600
          register: packages_installed
          when: ansible_facts['system_vendor'] == "QEMU" or ansible_facts['virtualization_type'] == "kvm"
          notify: Restart qemu-guest-agent

        - name: Start and enable qemu-guest-agent (Proxmox VMs only)
          service:
            name: qemu-guest-agent
            state: started
            enabled: yes
          when: ansible_facts['system_vendor'] == "QEMU" or ansible_facts['virtualization_type'] == "kvm"

  handlers:
    - name: Restart qemu-guest-agent
      service:
        name: qemu-guest-agent
        state: restarted
      when: packages_installed.changed
