- name: Install docker on Ubuntu server
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  tasks:

    - name: install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
        update_cache: yes

    - name: add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: true
    
    
    - name: add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: update apt cache
      apt:
        update_cache: yes

    - name: install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
          - docker-buildx-plugin
        update_cache: yes

    # add the current user to the docker group
    - name: add current user to docker group
      ansible.builtin.user:
        name: "{{ ansible_env.SUDO_USER }}"
        groups: docker
        append: yes
