---
- name: Update Ubuntu server
  hosts: all
  become: yes
  become_method: sudo
  #become_user: root
  vars:
    auto_reboot: false
    reboot_timeout: 300
    pre_update_snapshot: false
  
  tasks:
    - name: gather package facts
      package_facts:
        manager: apt
      
    - name: update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      register: apt_cache_update
      
    - name: check for upgradable packages
      shell: apt list --upgradable 2>/dev/null | grep -v "Listing" | wc -l
      register: upgradable_count
      changed_when: false
      
    - name: display upgradable packages count
      debug:
        msg: "{{ upgradable_count.stdout }} packages available for upgrade"
    
    - name: upgrade all apt packages
      apt:
        upgrade: dist
        update_cache: no
        autoremove: yes
        autoclean: yes
      register: apt_upgrade_result
      when: upgradable_count.stdout | int > 0
      
    - name: display upgrade summary
      debug:
        msg: 
          - "Packages upgraded: {{ apt_upgrade_result.changed | default(false) }}"
          - "Upgrade completed at: {{ ansible_date_time.iso8601 }}"
      when: apt_upgrade_result is defined
    
    - name: check if system reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      
    - name: check which packages require reboot
      shell: cat /var/run/reboot-required.pkgs 2>/dev/null || echo "none"
      register: reboot_packages
      changed_when: false
      when: reboot_required.stat.exists
      
    - name: display reboot requirement status
      debug:
        msg:
          - "Reboot required: {{ reboot_required.stat.exists }}"
          - "Packages requiring reboot: {{ reboot_packages.stdout_lines | default(['none']) }}"
    
    - name: send notification if reboot required
      debug:
        msg: "WARNING: System {{ inventory_hostname }} requires a reboot!"
      when: reboot_required.stat.exists
      
    - name: reboot system if required and auto_reboot is enabled
      reboot:
        msg: "Rebooting system to apply updates"
        reboot_timeout: "{{ reboot_timeout }}"
        pre_reboot_delay: 10
        post_reboot_delay: 30
      when: 
        - reboot_required.stat.exists
        - auto_reboot | bool
      register: reboot_result
      
    - name: verify system is back online after reboot
      wait_for_connection:
        timeout: 300
        delay: 10
      when: reboot_result is changed
      
    - name: gather final system facts
      setup:
      when: reboot_result is changed
      
    - name: display post-reboot information
      debug:
        msg:
          - "System successfully rebooted"
          - "Current uptime: {{ ansible_uptime_seconds }} seconds"
          - "Kernel version: {{ ansible_kernel }}"
      when: reboot_result is changed
      
    - name: check for failed services after updates
      shell: systemctl --failed --no-pager --no-legend | wc -l
      register: failed_services
      changed_when: false
      
    - name: display failed services warning
      debug:
        msg: "WARNING: {{ failed_services.stdout }} failed services detected. Run 'systemctl --failed' to investigate."
      when: failed_services.stdout | int > 0
      
    - name: create update log entry
      lineinfile:
        path: /var/log/ansible-updates.log
        line: "{{ ansible_date_time.iso8601 }} - Updates applied by Ansible - Reboot required: {{ reboot_required.stat.exists }} - Auto-rebooted: {{ reboot_result is changed }}"
        create: yes
        mode: '0644'
      ignore_errors: yes
