- hosts: all
  become: yes
  tasks:
    - name: upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600  # Only update cache if older than 1 hour
    
    - name: check if system reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
    
    - name: notify if reboot is required
      debug:
        msg: "Reboot required on {{ inventory_hostname }}"
      when: reboot_required.stat.exists
    
    - name: reboot system if required
      reboot:
        msg: "Rebooting to apply updates"
        reboot_timeout: 300
      when: reboot_required.stat.exists and auto_reboot | default(false)
